[package]
name = "quic-frp"
version = "0.1.5"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bincode = "2.0.1"
clap = { version = "4.5.53", features = ["derive"] }
compio = { git = "https://github.com/compio-rs/compio.git", branch = "master", features = [
    "runtime",
    "macros",
    "io-uring",
    "time",
    "rustls"
] }
compio-dispatcher = {git = "https://github.com/compio-rs/compio.git", branch = "master"}
compio-net = {git = "https://github.com/compio-rs/compio.git", branch = "master"}
compio-quic = { git = "https://github.com/compio-rs/compio.git", branch = "master", default-features = false, features = ["ring", "native-certs", "platform-verifier"] }
compio-signal = {git = "https://github.com/compio-rs/compio.git", branch = "master"}
dashmap = "6.1.0"
futures = "0.3.31"
libc = "0.2.178"
notify = "8.2.0"
rcgen = "0.14.5"
rustls = { version = "0.23.35", default-features = false, features = ["ring", "tls12"] }
rustls-pemfile = "2.2.0"
serde = {version = "1.0.228", features=["serde_derive"]}
socket2 = "0.6.1"
toml = "0.9.8"
tracing = "0.1.43"
tracing-subscriber = "0.3.22"
uuid = {version = "1.19.0", features=["v4"]}

[profile.release]
opt-level = "z"
strip = true
